apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-middleware.names.fullname" . }}
  labels:
{{ include "frontend-middleware.labels.standard" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
{{ include "frontend-middleware.labels.matchLabels" . | indent 4 }}

